### PR TITLE
switch to OSDI-API-Token header for auth in person signup helper

### PR DESCRIPTION
**Pull request by joshco**
made change or person signup helper.  TODO generalize for other operations

### CODE REVIEW

**Comment by BaconSoap** [comment]
:+1: - minor note: we can remove the `require('auth')` part from line 6

not-blocking-this-PR-note: we should apply the same change to [this](https://github.com/NGPVAN/osdi-service/blob/feature/clientRefactor/lib/van-request-helper.js#L61)

**Comment by shaisachs** [comment]
Hi there, I'm closing this PR because it was written against feature/clientRefactor, but the code that's "live" on osdi.ngpvan.com is in the develop branch.  However, I did port Josh's changes to the develop branch, tested them locally, and pushed just now, so they should be live shortly.

For the near-term future (next few weeks) PRs intended to affect osdi.ngpvan.com should be written against the develop branch.

**Comment by joshco** [comment]
PR updated as requested

**Comment by joshco** [comment]
ahh.  ok

**Pull request closed without merging**
